lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, friend_list_json
from.views import get_mahasiswa_list, get_mahasiswa_detail

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add-friend/$', add_friend, name='add-friend'),
	url(r'^validate-npm/$', validate_npm, name='validate-npm'),
	url(r'^delete-friend/$', delete_friend, name='delete-friend'),
	url(r'^friend-list/$', friend_list, name='friend-list'),
	url(r'^get-friend-list/$', friend_list_json, name='get-friend-list'),
	url(r'^get-mahasiswa-list/', get_mahasiswa_list, name='get-mahasiswa-list'),
	url(r'^mahasiswa/([0-9]{10})/$', get_mahasiswa_detail, name='get-mahasiswa-detail')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    url(r'^$', RedirectView.as_view(url='lab-4/', permanent='true'), name='index')
]

lab_7/models.py
from django.db import models
import json

class Friend(models.Model):
	friend_name = models.CharField(max_length=400)
	npm = models.CharField(max_length=250, primary_key=True)
	added_at = models.DateField(auto_now_add=True)

	def as_json_string(self):
		data = {"friend_name" : self.friend_name, "npm" : self.npm, "added_at": str(self.added_at)}
		return json.dumps(data)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

author = "Ahmad Hasan Siregar"
response = {"author": author}
csui_helper = CSUIhelper()

# Page halaman menampilkan list mahasiswa yang ada
def index(request):
	mahasiswa_list = csui_helper.instance.get_mahasiswa_list(1)

	friend_list = Friend.objects.all()
	response = {"mahasiswa_list": mahasiswa_list, "friend_list": friend_list, "author" : author}
	html = 'lab_7/lab_7.html'
	return render(request, html, response)

def get_mahasiswa_list(request):
	if request.method == 'GET':
		pageNumber = int(request.GET.get("page", 1))
		if 1 <= pageNumber <= 68:
			mahasiswa_list = csui_helper.instance.get_mahasiswa_list(pageNumber)
			data = {'mahasiswa_list': mahasiswa_list}
			return JsonResponse(data)
		else:
			return HttpResponseRedirect('/lab-7/')

def get_mahasiswa_detail(request, npm):
	if request.method == 'GET':
		mahasiswa = csui_helper.instance.get_mahasiswa_detail(npm)
		response["mahasiswa"] = mahasiswa
		html = "lab_7/detail_mahasiswa.html"

		return render(request, html, response)

def friend_list(request):
	friend_list = Friend.objects.all()
	response['friend_list'] = friend_list
	html = 'lab_7/daftar_teman.html'
	return render(request, html, response)

def friend_list_json(request):
	data = {
		'friend_list': models_to_json_array(Friend.objects.all())
	}
	return JsonResponse(data)

@csrf_exempt
def add_friend(request):
	if request.method == 'POST':
		name = request.POST['name']
		npm = request.POST['npm']
		# friend already exist
		if (Friend.objects.filter(npm=npm).exists()):
			return HttpResponse("Mahasiswa sudah ditambah menjadi teman", status=400)
		# friend not yet in db
		else:
			friend = Friend(friend_name=name, npm=npm)
			friend.save()
			data = friend.as_json_string()
			return HttpResponse(data)

@csrf_exempt
def delete_friend(request):
	if request.method == 'POST':
		Friend.objects.filter(npm=request.POST["npm"]).delete()
		data = {"deleted_npm" : request.POST["npm"]}
		return JsonResponse(data)

@csrf_exempt
def validate_npm(request):
	npm = request.POST.get('npm', None)
	data = {
		'is_taken': Friend.objects.filter(npm=npm).exists()
	}
	return JsonResponse(data)

def models_to_json_array(obj):
	data = []
	for mhs in obj:
		data.append(json.loads(mhs.as_json_string()))
	return data

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: "{% url 'lab-7:get-friend-list' %}",
                dataType: "json",
                success: function (response) {
                    response.friend_list.forEach(function(friend) {
                        html = '<a id="friend-' + friend.npm + '" class="list-group-item clearfix" href="mahasiswa/' + friend.npm + '/">' +
                            friend.friend_name + ' (' + friend.npm +
                            `)<span class="pull-right"><span class="btn btn-xs btn-default" onClick="deleteFriend('` + friend.npm + `')">Hapus teman</span></span></a>`;
                        $("#friend-list").append(html)
                    });
                },
                error: function(error){
                    alert("Daftar teman tidak bisa didapatkan saat ini")
                }
            });
        });

        var deleteFriend = function(npm) {
            $.ajax({
                method: "POST",
                url: "{% url 'lab-7:delete-friend' %}",
                data: {"npm": npm},
                dataType: "json",
                success : function (response) {
                    console.log(typeof response);
                    console.log(response);
                    
                    // delete friend in list
                    $("#friend-" + response.deleted_npm).remove();
                },
                error : function (error) {
                    console.log(error);
                    alert(error.responseText);
                }
            });
        };
    </script>
{% endblock %}

lab_7/templates/lab_7/detail_mahasiswa.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
	Nama: {{ mahasiswa.nama }}<br>
	NPM: {{ mahasiswa.npm }}<br>
	Alamat: {{ mahasiswa.alamat_mhs }}<br>
	TTL: {{ mahasiswa.kota_lahir }}, {{ mahasiswa.tgl_lahir }}<br>

	Peta alamat:
	<div id="map-alamat"></div>
{% endblock %}
{% block javascript %}
    <script>
		function initMap() {
			var encodedAdress = encodeURI("{{mahasiswa.alamat_mhs}}".slice(0, 20));
			var apiKey = "AIzaSyDdkOgCZIHtB-wKtnc_LN-dSoXoUx_c_go";			
			console.log(encodedAdress);

			$.ajax({
				method: "GET",
				url: "https://maps.googleapis.com/maps/api/geocode/json?address="+ encodedAdress + " &key="+ apiKey,
				dataType: "json",
				success: function(response) {
					console.log(response);
					var myLatLng;

					if (response.status === "OK") 
						myLatLng = response.results[0].geometry.location;
					else {
						myLatLng = {"lat" : -6.3627638, "lng" : 106.8270482};
						alert("Oops! Alamat tidak dapat ditemukan");
					}
					console.log(myLatLng);
					// Create a map object and specify the DOM element for display.
					var map = new google.maps.Map(document.getElementById('map-alamat'), {
						center: myLatLng,
						zoom: 15
					});

					// Create a marker and set its position.
					var marker = new google.maps.Marker({
						map: map,
						position: myLatLng,
						title: 'Hello World!'
					});
				},
				error: function(error) {
					alert("Oops! Alamat saat ini tidak dapat ditemukan");
				}
			});
		};
    </script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDdkOgCZIHtB-wKtnc_LN-dSoXoUx_c_go&callback=initMap"
    async defer></script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    	<div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <ul class="pagination">
                	<li><a class="btn" onClick="prevPage()"><<</a></li>
				    <li class="active"><a id="page-number">1</a></li>
				    <li><a class="btn" onClick="nextPage()">>></a></li>
                </ul>
                <div id="mahasiswa-entry-group" class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix mahasiswa-entry">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Oops!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Oops!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
	var pageNumber = 1;

	var nextPage = function() {
		if (pageNumber <= 68) {
			$.ajax({
				method: "GET",
				url: "{% url 'lab-7:get-mahasiswa-list' %}?page=" + (pageNumber+1),
				dataType: "json",
				success: function(response) {
					pageNumber++;
					if (pageNumber > 68) pageNumber = 68;

					$("#page-number").text(pageNumber);
					$(".mahasiswa-entry").remove();
					response.mahasiswa_list.forEach(function(mahasiswa) {
						html = `<a class="list-group-item clearfix mahasiswa-entry">` + mahasiswa.nama + ` (` + mahasiswa.npm + `)<span class="pull-right"><span class="btn btn-xs btn-default" onClick="addFriend('` + mahasiswa.nama + `', '` + mahasiswa.npm + `')">Tambah sebagai teman</span></span></a>`;
						$("#mahasiswa-entry-group").append(html);
					});
				}
			});
		}
	};

	var prevPage = function() {
		if (pageNumber > 1) {
			$.ajax({
				method: "GET",
				url: "{% url 'lab-7:get-mahasiswa-list' %}?page=" + (pageNumber-1),
				dataType: "json",
				success: function(response) {
					pageNumber--;
					if (pageNumber < 1) pageNumber = 1;

					$("#page-number").text(pageNumber);
					$(".mahasiswa-entry").remove();
					response.mahasiswa_list.forEach(function(mahasiswa) {
						html = `<a class="list-group-item clearfix mahasiswa-entry">` + mahasiswa.nama + ` (` + mahasiswa.npm + `)<span class="pull-right"><span class="btn btn-xs btn-default" onClick="addFriend('` + mahasiswa.nama + `', '` + mahasiswa.npm + `')">Tambah sebagai teman</span></span></a>`;
						$("#mahasiswa-entry-group").append(html);
					});
				}
			});
		}
	};

    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm},
            dataType: "json",
            success : function (friend) {
            	// append friend to list
                html = '<a class="list-group-item clearfix">' +
                    friend.friend_name + ' (' + friend.npm +
                    ')</a>';
                $("#friend-list").append(html);
            },
            error : function (error) {
            	console.log(error);
                alert(error.responseText);
            }
        });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val();
       npm = $("#field_npm").val();
        addFriend(name, npm);
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}